server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://auth-service/realms/pagamento

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
