server:
  port: 8082
spring:
  application:
    name: payment-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost/payment_service
    username: user
    password: pass
