server:
  port: 8086
spring:
  application:
    name: asaas-integration
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost/asaas_integration
    username: user
    password: pass
