version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: pagamento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
