apiVersion: v1
kind: Secret
metadata:
  name: pagamento-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "cGFnYW1lbnRv"  # pagamento
  SPRING_DATASOURCE_PASSWORD: "c2VjcmV0"      # secret
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NybS5TY3JtTG9naW5Nb2R1bGUgcmVxdWlyZSB1c2VybmFtZT0iVVNFUiIgcGFzc3dvcmQ9IlBBU1NXT1JEIg=="
  JWT_SECRET_KEY: "c3VwZXJfc2VjcmV0X2tleV8xMjM0NTY3OA=="  # super_secret_key_12345678
