name: Auth Service CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'auth-service/**'
      - 'common/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'auth-service/**'
      - 'common/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service
  K8S_NAMESPACE: pagamento-production
  APP_NAME: auth-service

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B clean package -DskipTests -f auth-service/pom.xml
      
    - name: Run Unit Tests
      run: mvn -B test -f auth-service/pom.xml -Dspring.profiles.active=test
      
    - name: Run Integration Tests
      run: |
        mvn -B verify -f auth-service/pom.xml -Dspring.profiles.active=test -Dspring.datasource.url=jdbc:postgresql://localhost:5432/testdb
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: auth-service
        
  docker-build-push:
    name: Build and Push Docker Image
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: auth-service
        file: auth-service/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
        build-args: |
          JAR_FILE=target/auth-service-*.jar
          
  deploy-staging:
    name: Deploy to Staging
    needs: docker-build-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.STAGING_KUBECONFIG }}
        
    - name: Deploy to Kubernetes
      uses: k8s-deploy-action@v1.2
      with:
        namespace: ${{ env.K8S_NAMESPACE }}
        manifests: |
          deployment/k8s/auth-deployment.yaml
        images: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
        
  deploy-production:
    name: Deploy to Production
    needs: [build-test, docker-build-push, deploy-staging]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Wait for Staging Tests
      run: |
        echo "Waiting for staging health checks..."
        sleep 300  # Simula espera por testes
        
    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.PRODUCTION_KUBECONFIG }}
        
    - name: Deploy to Kubernetes
      uses: k8s-deploy-action@v1.2
      with:
        namespace: ${{ env.K8S_NAMESPACE }}
        manifests: |
          deployment/k8s/auth-deployment.yaml
        images: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
